- name: Install and run nginx
  become: yes
  hosts: mongodb
  tasks: 
      - name: Installing nginx
        ansible.builtin.yum:
         name: nginx
         state: installed
      - name: Run nginx
        ansible.builtin.service:
          name: nginx
          state: started

